### ISSUE TITLE
Folder does not generate

### ISSUE THREAD

**Issue by Chaoscent** [Toxnix/BanSystem#4]
I put the jar file in the plugins folder, started the server and there wasnt a BanSystem folder. When doing /plugin ingame it also doesnt show up. In the Console there is this: 
![image](https://github.com/Toxnix/BanSystem/assets/150971099/ef9f82eb-287e-45af-bf8b-bb55ab50cdef)

**Additional context**
I use GeyserMC

**Comment by BachErik** [comment]
This is a plugin for BungeeCord only. I am currently working on a larger feature and plan to support other known server forms in the future, as well as paper.
